export const API = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  ME: "/user/me",
  CREATE_QUALIFICATION: "/qualification",
  GET_QUALIFICATION: "/qualification",
  UPDATE_QUALIFICATION: (id: string) => `/qualification/${id}`,
  DELETE_QUALIFICATION: (id: string) => `/qualification/${id}`,
  CREATE_CONTACT: "/contact",
  GET_CONTACT: "/contact",
  UPDATE_CONTACT: (id: string) => `/contact/${id}`,
  DELETE_CONTACT: (id: string) => `/contact/${id}`,
  UPLOAD: "/upload",
  CREATE_DOCUMENT: "/document",
  GET_DOCUMENT: "/document",
  UPDATE_DOCUMENT: (id: string) => `/document/${id}`,
  DELETE_DOCUMENT: (id: string) => `/document/${id}`,
  CREATE_EMPLOYEE: "user/employee",
  GET_COMPANY_USERS: (query: string) => `user?${query}`,
  GET_EMPLOYEE: (id: string) => `user/employee/${id}`,
  DELETE_EMPLOYEE: (id: string) => `user/employee/${id}`,
  UPDATE_EMPLOYEE: (id: string) => `user/employee/${id}`,
  GET_COMPANY_ADDITIONAL_DATA: (companyId: string) =>
    `/company/data/${companyId}`,
  GET_CLAIM_TYPES: `claim-type`,
  GET_CLAIMS: `claim`,
  MUTATE_CLAIM: `claim`,
  DELETE_CLAIM: (id: string) => `claim/${id}`,
  GET_COMMISSIONS: () => `commission`,
  CREATE_COMMISSION: "commission",
  UPDATE_COMMISSION: (id: string) => `commission/${id}`,
  DELETE_COMMISSION: (id: string) => `commission/${id}`,
  MUTATE_LEAVE: () => `leave`,
  DELETE_LEAVE: (id: string) => `leave/${id}`,
  APPROVE_LEAVE: (id: string) => `leave/approve/${id}`,
  GET_LEAVES: () => `leave`,
  GET_LEAVE_DETAILS: (id: string) => `leave/user/${id}`,
  GET_ADMIN_DASHBOARD_DATA: () => `dashboard`,
};
