import { addressTypesEnum } from "@/enums/address-types.enum";
import { countriesEnum } from "@/enums/countries.enum";
import { gendersEnum } from "@/enums/genders.enum";
import { identitiesEnum } from "@/enums/identities.enum";
import { maritalStatusesEnum } from "@/enums/marital-statuses.enum";
import { nationalitiesEnum } from "@/enums/nationalities.enum";
import { raceEnum } from "@/enums/race.enum";
import { rolesEnum } from "@/enums/roles.enum";
import { BaseType } from "./base.type";
import { Company, CompanyWithNecessaryFields } from "./company.type";
import { Bank, BankWithNecessaryFields } from "./bank.type";
import { Job, JobWithNecessaryFields } from "./job.type";
import { WorkTable, WorkTableWithNecessaryFields } from "./work-table.type";
import { LeaveTable, LeaveTableWithNecessaryFields } from "./leave-table.type";
import { Employment, EmploymentWithNecessaryFields } from "./employment.type";
import {
  Qualification,
  QualificationWithNecessaryFields,
} from "./qualification.type";
import { Contact, ContactWithNecessaryFields } from "./contact.type";
import { Document, DocumentWithNecessaryFields } from "./document.type";

export type User = BaseType & {
  name: string;
  email: string;
  password?: string;
  isEmailVerified: boolean;
  identityNumber: string;
  identityType: identitiesEnum | string;
  dateOfBirth?: Date;
  addressType?: addressTypesEnum | string;
  country?: countriesEnum | string;
  address: string;
  postalCode?: string;
  city?: string;
  state?: string;
  houseNo?: string;
  levelNo?: string;
  unitNo?: string;
  gender?: gendersEnum | string;
  race?: raceEnum | string;
  mobileNumber?: string;
  roles: rolesEnum[] | string[];
  avatar?: string;
  nationality?: nationalitiesEnum | string;
  maritalStatus?: maritalStatusesEnum | string;
  cpfNumber?: string;
  taxNumber?: string;
  allowLogin?: boolean;
  optionalEmail?: string;
  employerPaysCpf?: boolean;
  prEffectiveDate?: Date | null;
  allowanceCommission?: number;
  allowanceErrorFee?: number;
  deductionCdac?: number;
  deductionEcf?: number;
  deductionMbmf?: number;
  deductionEcfSinda?: number;
  maxPayToCalculate?: number;
  noSdlContribution?: boolean;
  noShgContribution?: boolean;
  useAttendanceRecords?: boolean;
  isNonResidentialDirector?: string;
  homeTelephoneNumber?: string;
  workTelephoneNumber?: string;

  // Relations
  bank?: Bank | BankWithNecessaryFields;
  job?: Job | JobWithNecessaryFields;
  workTable?: WorkTable | WorkTableWithNecessaryFields;
  leaveTable?: LeaveTable | LeaveTableWithNecessaryFields;
  employment?: Employment | EmploymentWithNecessaryFields;
  qualifications?: Array<Qualification | QualificationWithNecessaryFields>;
  contacts?: Array<Contact | ContactWithNecessaryFields>;
  documents?: Array<Document | DocumentWithNecessaryFields>;
  payslips?: string[];
  commissions?: string[];
  claims?: string[];
  overtimes?: string[];
  todos?: string[];
  leaves?: string[];
  company?: Company | CompanyWithNecessaryFields;
};
