import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import QueryProvider from "../providers/query-provider";
import { UserProvider } from "../context/user-context";
import Header from "@/components/header";
import { cn } from "@/lib/utils";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <div className={cn("h-dvh max-h-dvh flex flex-col")}>
          <Header />
          <div className={cn("h-full mt-12")}>
            <QueryProvider>
              <UserProvider>{children}</UserProvider>
            </QueryProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
